version: '3.8'

services:
  nomina:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nomina-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
